import localFont from "next/font/local";
import "./css/globals.css";

const geistPressStart = localFont({
  src: "./fonts/PressStart2P-Regular.ttf",
  variable: "--font-geist-PressStart",
  weight: "100 900",
});
const geistPixelifySans = localFont({
  src: "./fonts/PixelifySans-VariableFont_wght.ttf",
  variable: "--font-geist-PixelifySnas",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistPressStart.variable} ${geistPixelifySans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
